### ISSUE TITLE
Italic numbers not working

### ISSUE THREAD

**Issue by JasonAtATL** [khaledhosny/amiri-font#238]
Hello,

We have a client that would like to use Amari, but unfortunately it doesn't appear italic numbers render correctly. It also appears that italicized exclamation points are angled in the wrong direction (left instead of right). We're using the latest version of the Amari font (0.117), and we've tried several previous versions with the same result.

Here's what we see in Microsoft Word on PC:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/5066697/183706468-541e0728-ae17-42cb-8cd1-42fadca4d534.png">

**Comment by alerque** [comment]
I don't speak Arabic, but a few things seem wrong with this test:

* Don't use MS Word to test font feature support. Test something else then check if you can get it to also work in Word if that's what you need. Just don't blame fonts when Word does the wrong thing.

* Testing an Arabic font and using Latin glyphs to pronounce it doesn't support something isn't the right way.

* Depending on how your language is set, following up Arabic numerals (which BiDi is going to suggest be LTR) with punctuation (which can be either depending on what came before them) is going to mess you up. Ironically in this case Word seems to have done the wrong thing 3 times over and come up with the wrong answer by virtue of circling back around.

My testing suggests Amiri might have had slanted digits in 1.113. I updated to 1.117 and they went away in my test. I suspect there was a good reason for that, likely the unpredictability of which way they would slant in a BiDi environment (never mind Word).

Here is a test document you can save as `test.sil`:

```sile
\begin[papersize=a7]{document}
\nofolios
\neverindent
\use[module=packages.frametricks]
\language[main=en]

\font[family=Amiri]
Testing 0123456789 testing!!!\cr
\font[style=Slanted]{Testing 0123456789 testing!!!}

\bigskip
\breakframevertical

\thisframeRTL
\language[main=ar]

اختبار 0123456789 اختبار!!!\cr
\font[style=Slanted]{اختبار  0123456789 اختبار!!!}

\end{document}
```

...and render with:

```console
$ sile -d versions test.sil
SILE v0.14.1 (Lua 5.4)
<test.sil> as sil

! Unable to load language feature support (e.g. hyphenation rules) for ar: module 'languages.ar' not found at test.sil:15:1: in \language[main="ar"]
[1]
Harfbuzz version: 5.1.0
Shapers enabled: graphite2, ot, fallback
ICU support enabled

Fonts used:
/usr/share/fonts/TTF/Amiri-Slanted.ttf:0        Version 0.117
/usr/share/fonts/TTF/Amiri-Slanted.ttf:0        Version 0.117
/usr/share/fonts/TTF/Amiri-Regular.ttf:0        Version 0.117
/usr/share/fonts/TTF/Amiri-Regular.ttf:0        Version 0.117
```

To get a PDF [`test.pdf`](https://github.com/aliftype/amiri/files/9293936/test.pdf) that looks like this:

![image](https://user-images.githubusercontent.com/173595/183741634-2750085b-1f24-4b9a-9ae9-49438fe99e50.png)

Maybe not what you will use later, but probably a better test of what's going on in the font ;-)

**Comment by khaledhosny** [comment]
Amiri’s Arabic and Latin are tilted in the opposite directions, and this poses a problem for characters shared between the two scripts (like punctuation and digits).

Ideally the font can have two sets of the shared glyphs, each titled appropriately for each script, and switch them using appropriate OpenType substitutions.  This, in fact, what early versions of Amiri, but it did not work well in practice since it requires rigorous and consistent handling of script-common characters across applications. Some applications, instead, always treated digits as Latin, so digits in Arabic text get tilted in the wrong direction. Others handle punctuation inconsistently. e.g. “ARABIC (latin)̦” would end with each parenthesis titled in a different direction.

So, current versions of Amiri keep all such characters upright as a compromise. Upright punctuation in Italic is not unheard of, though it is probably considered old-fashioned now, upright digits in italic are probably rarer, but I didn’t have much choice here.

**Comment by JasonAtATL** [comment]
@alerque we were also seeing this behavior in PDFs, which is our actual use case. I just thought MS Word would be an easier repro for most people.

@khaledhosny, thank you for the detailed response. I'll pass this information on to our client and let them decide how they'd like to proceed.

**Comment by khaledhosny** [comment]
I forgot to mention that you should be getting an upright exclamation mark if you are using the latest version, so make sure you don’t have cache issue or multiple versions of the font installed.
