### ISSUE TITLE
Why doesn't the Amiri Quran font have a bold and slanted variant

### ISSUE THREAD

**Issue by amarz45** [khaledhosny/amiri-font#244]
I was wondering why the Amiri Quran version does not have a bold and slanted variant, only a coloured variant. I am typesetting the Quran in a LaTeX book and I want to have the surah names in bold, but there is no bold variant for the Quran font. Of course, I can fake the boldness when declaring `\newfontfamily\arabicfont`, but I would prefer not to do that.

**Comment by khaledhosny** [comment]
Because I haven’t seen anyone set Quranic text in bold or italic. Surah names are not part of the Quranic text, so they should be set in the regular Amiri fonts. Any why the difference between the Amiri and Amiri Quran these days is mainly smaller marks and some disabled ligatures, the Quranic orthographic needs are better represented by relevant Unicode characters and conventions, so you can probably get away with setting Quranic text in the regular Amiri fonts as well.

**Comment by amarz45** [comment]
> Surah names are not part of the Quranic text, so they should be set in the regular Amiri fonts.

Thanks, I will typeset the ayat in Amiri Quran and the surah names in Amiri.
