### ISSUE TITLE
[flutter] : The font color is fixed and white

### ISSUE THREAD

**Issue by ahmetsametoglu** [khaledhosny/amiri-font#264]
Hello,

I am developing an application in Flutter and I want to use the font [Amiri Quran](https://fonts.google.com/specimen/Amiri+Quran?query=amiri) The font color is fixed and white. There is no problem with the Amiri font but the color does not change in Amiri Quran. Are you aware of such a problem?

**Comment by khaledhosny** [comment]
The version of Amiri Quran on Google Fonts is a [color font](https://fonts.google.com/knowledge/introducing_type/introducing_color_fonts), where dots and vowels marks and some other symbols get different colors. Some applications of frameworks might not correctly handle such fonts. If you are not interested in the color font aspect, you can use the version from this repository, otherwise I think you need to report this against Flutter as it looks like a bug.
